version: "3.9"

services:
  app:
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 5000:5000

  db:
    container_name: postgres_app
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: orders_db
    volumes:
      - postgress-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgress-data:
    driver: local
